# Test Kinematica

Een steen wordt vanop de top van een gebouw (45.0 m hoog) weggegooid onder een hoek van 30.0° met de horizontaal. De steen heeft een initiële snelheid gelijk aan 20.0 m/s.
- Hoe lang duurt het tot de steen op de grond valt?
- Wat is de snelheid van de steen juist voordat hij op de grond valt?

## Oplossing

Gegeven is: $h = 45.0$ m, $\theta = 30.0$° en $v_0 = 20.0$ m/s. Laten we deze input eerst definiëren in Octave, samen met de gravitatieversnelling $g = 9.81$ m/s$^2$:

In [1]:
h = 45;
theta = 30/180*pi;
v0 = 20;
g = 9.81;

We starten zoals gewoonlijk met de bewegingsvergelijkingen:

\begin{cases}
  x(t) = x_0 + v_{x0}t + a_{x}t^2 = v_0 \cos\theta t\\    
  y(t) = y_0 + v_{y0}t + a_{y}t^2 = h + v_0 \sin\theta t - \frac{1}{2} g t^2
\end{cases}

We zoeken het tijdstip waarop de steen op de grond valt. Dit komt overeen met $y(t) = 0$:

\begin{align}
y(t) = 0 &\Leftrightarrow h + v_0 \sin\theta t - \frac{1}{2} g t^2 = 0 \\
&\Leftrightarrow \frac{1}{2} g t^2 - v_0 \sin\theta t - h = 0
\end{align}

Dit is een vierkantsvergelijking met $a = \frac{g}{2}$, $b = - v_0 \sin\theta$ en $c = -h$. Laten we deze even snel oplossen in Octave:

In [2]:
a = g/2; b = -v0 * sin(theta); c = -h;
D = sqrt(b^2 - 4*a*c) % De discriminant
t1 = (-b + D)/(2*a), t2 = (-b - D)/(2*a)

D =  31.351
t1 =  4.2152
t2 = -2.1765


$t_1$ is het tijdstip dat we zoeken. Om de snelheid te vinden gebruiken we:

\begin{cases}
  v_x(t) = v_{x0} + a_{x}t = v_0 \cos\theta \\    
  v_y(t) = v_{y0} + a_{y}t = v_0 \sin\theta - g t
\end{cases}

En de uitdrukking voor de grootte van de vector $|\vec{v}| = \sqrt{v_x^2 + v_y^2}$:

In [3]:
vx = v0*cos(theta)
vy = v0*sin(theta)-g*t1
v = sqrt(vx^2 + vy^2)

vx =  17.321
vy = -31.351
v =  35.818


De finale oplossingen zijn dus $t = 4.22$ s en $|\vec{v}| = 35.8$ m/s.